#微服务示例：积分服务
spring:
  application:
    name: point-service
  profiles:
    active: dev

server:
  port: 8811

#配置使用okhttp替换默认的http client
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
ConnectTimeout: 10000
ReadTimeout: 30000
MaxAutoRetries: 0
MaxAutoRetriesNextServer: 1

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000