#微服务示例：积分服务
spring:
  application:
    name: point-service
  profiles:
    active: dev

server:
  port: 8811

#配置使用okhttp替换默认的http client
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

