spring:
  application:
    name: gateway-server
  profiles:
    active: dev

server:
  port: 8711

#通过service id从eureka自动发现服务
#如果不配置这个，zuul也会从eureka自动获取服务列表，使用serviceId作为path映射，可以通过这个映射不同的path
zuul:
  routes:
    account-service:
      serviceId: account-service
      path: /account/**
    point-service:
      serviceId: point-service
      path: /point/**
  host: #修改默认超时时间，避免服务启动第一次加载时超时
    socket-timeout-millis: 30000
    connect-timeout-millis: 10000
    max-total-connections: 200
    max-per-route-connections: 20

#配置使用okhttp替换默认的http client
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
ConnectTimeout: 10000
ReadTimeout: 30000
MaxAutoRetries: 0
MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000