version: '2'

services:
  #服务注册中心2台，相互注册
  registry-server1:
    image: liuli/spring-cloud-registry
    hostname: registry-server1
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=ha1
  registry-server2:
    image: liuli/spring-cloud-registry
    hostname: registry-server2
    ports:
      - "8762:8761"
    environment:
      - spring.profiles.active=ha2

  #账户服务1台
  account-server1:
      image: liuli/account-service
      hostname: account-server1
      ports:
        - "8801:8801"
      environment:
        - spring.profiles.active=ha1

  #服务网关2台，对内作为普通的微服务注册到eureka，对外需要使用nginx做反向代理
  gateway-server1:
    image: liuli/spring-cloud-gateway
    hostname: gateway-server1
    ports:
      - "8711:8711"
    environment:
      - spring.profiles.active=ha1
  gateway-server2:
    image: liuli/spring-cloud-gateway
    hostname: gateway-server2
    ports:
      - "8712:8711"
    environment:
      - spring.profiles.active=ha2