services:
  registry-server1:
    image: liuli/spring-cloud-registry
    ports:
      - "1111:1111"
    environment:
      - spring.profiles.active=registry_ha_1
  registry-server2:
    image: liuli/spring-cloud-registry
    ports:
      - "1112:1111"
    environment:
      - spring.profiles.active=registry_ha_2