version: '2'

#完整环境配置，包括注册中心，服务网关，服务节点，服务跟踪，熔断监控，监控聚合器
services:
  #服务注册中心2台，相互注册
  registry-server1:
    image: liuli/spring-cloud-registry
    hostname: registry-server1
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=ha1
  registry-server2:
    image: liuli/spring-cloud-registry
    hostname: registry-server2
    ports:
      - "8762:8761"
    environment:
      - spring.profiles.active=ha2

  #积分服务2台
  point-server1:
    image: liuli/point-service
    hostname: point-server1
    ports:
      - "8811:8811"
    environment:
      - spring.profiles.active=ha1
  point-server2:
    image: liuli/point-service
    hostname: point-server2
    ports:
      - "8812:8811"
    environment:
      - spring.profiles.active=ha1

  #账户服务2台
  account-server1:
      image: liuli/account-service
      hostname: account-server1
      ports:
        - "8801:8801"
      environment:
        - spring.profiles.active=ha1
  account-server2:
      image: liuli/account-service
      hostname: account-server2
      ports:
        - "8802:8801"
      environment:
        - spring.profiles.active=ha1

  #服务网关2台，对内作为普通的微服务注册到eureka，对外需要使用nginx做反向代理
  gateway-server1:
    image: liuli/spring-cloud-gateway
    hostname: gateway-server1
    ports:
      - "8711:8711"
    environment:
      - spring.profiles.active=ha1

  #服务跟踪1台，zipkin
  zipkin-server:
    image: liuli/spring-cloud-zipkin
    hostname: zipkin-server
    ports:
      - "9411:9411"

  #熔断监控1台，hystrix dashboard
  monitor-server:
    image: liuli/spring-cloud-hystrix-dashboard
    hostname: monitor-server
    ports:
      - "9412:9412"

  #熔断监控聚合器1台，turbine
  turbine-server:
    image: liuli/spring-cloud-turbine
    hostname: turbine-server
    ports:
      - "9413:9413"