version: '2'

services:
  registry-server1:
    image: liuli/spring-cloud-registry
    hostname: registry-server1
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=registry_ha_1
  registry-server2:
    image: liuli/spring-cloud-registry
    hostname: registry-server2
    ports:
      - "8762:8761"
    environment:
      - spring.profiles.active=registry_ha_2

