#高可用配置2
eureka:
  instance:
    hostname: registry-server2
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     defaultZone: http://registry-server1:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0