#高可用配置1，相互注册
eureka:
  instance:
    hostname: ${registry_server_host:registry-server1}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     defaultZone: ${registry_server_url:http://registry-server2:${server.port}/eureka/}
    server:
      waitTimeInMsWhenSyncEmpty: 0