#微服务示例：账户服务
spring:
  application:
    name: account-service
  profiles:
    active: dev

server:
  port: 8801

#配置使用okhttp替换默认的http client
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  ConnectTimeout: 10000
  ReadTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000