apiVersion: v1
kind: Service
metadata:
  name: eureka-service-edu-1
#  namespace: edu-spring-cloud
spec:
  ports:
  - port: 8761  #服务端口
    targetPort: 8761  #pod端口
    nodePort: 30761  #节点对外开放端口
    #protocol: TCP
  selector:
    app: eureka-1
#  clusterIp:
  type: NodePort  #NodePort方式对外暴露端口


---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service-edu-2
#  namespace: edu-spring-cloud
spec:
  ports:
  - port: 8762  #服务端口
    targetPort: 8761
    nodePort: 30762
    #protocol: TCP
  selector:
    app: eureka-2
#  clusterIp:
  type: NodePort
