apiVersion: v1
kind: Service
metadata:
  name: eureka-service-edu-0
#  namespace: edu-spring-cloud
spec:
  ports:
  - port: 8761  #服务端口
    #protocol: TCP
  selector:
    app: eureka
#  clusterIp:
#  type: NodePort