apiVersion: v1
kind: Service
metadata:
  name: eureka-service-edu-0
#  namespace: edu-spring-cloud
spec:
  ports:
  - port: 8761
  selector:
    app: eureka
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service-edu-0
spec:
  selector:
    matchLabels:
      app: eureka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: registry-server1
        image: liuli/spring-cloud-registry
        imagePullPolicy: IfNotPresent
        env:
        - name: spring.profiles.active
          value: ha1
        ports:
        - containerPort: 8761
          name: registry-1