apiVersion: v1
kind: Service
metadata:
  name: zuul
#  namespace: z3-edu
spec:
  ports:
  - port: 8711  #服务端口
    targetPort: 8711  #pod端口
    nodePort: 30711  #节点对外开放端口
    #protocol: TCP
  selector:
    app: zuul
#  clusterIp:
  type: NodePort  #NodePort方式对外暴露端口
