spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8701/
      profile: default
      label: master
server:
  port: 8821

management:
  security:
    enabled: false