spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          #search-paths: xxx
          #username: xxx
          #password: xxx
server:
  port: 8701
